spring:
  datasource:
    username: root                # 기존 application.yml에서 빼낸 DB 계정
    password: yd157238+           # 기존 application.yml에서 빼낸 DB 비밀번호
  mail:
    username: ocid1.user.oc1…     # 기존 application.yml에서 빼낸 메일 서비스 계정
    password: i[0-fCt$ZW+((elj5g0Z # 기존 application.yml에서 빼낸 메일 서비스 비밀번호