server:
  port: 8081

spring:
  application:
    name: UserService
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:3306/lumidiary
      ?serverTimezone=Asia/Seoul
      &characterEncoding=utf8
      &useSSL=false
      &allowPublicKeyRetrieval=true
      &createDatabaseIfNotExist=true"
    username: root
    password: yd157238+
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.email.ap-chuncheon-1.oci.oraclecloud.com
    port: 587
    username: ${OCI_SMTP_USERNAME}
    password: ${OCI_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  from: admin@lumidiary.com

jwt:
  secret: mysecretkeymysecretkeymysecretkey123456
  expiration: 86400000
