server:
  port: 8081

spring:
  application:
    name: UserService
  config:
    import: optional:config/application-secret.yml
  jackson:
    serialization:
      # 날짜를 숫자(timestamp) 대신 "yyyy-MM-dd" 같은 문자열로 직렬화
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd   # 전역 날짜 포맷
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: "jdbc:mysql://10.0.10.210:3306/lumidiary 
      ?serverTimezone=Asia/Seoul
      &characterEncoding=utf8
      &useSSL=false
      &allowPublicKeyRetrieval=true
      &createDatabaseIfNotExist=true" #"jdbc:mysql://10.0.10.210:3306/lumidiary
    username: ${spring.datasource.username}   # 시크릿 파일에서 가져옴
    password: ${spring.datasource.password}   # 시크릿 파일에서 가져옴
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.email.ap-chuncheon-1.oci.oraclecloud.com
    port: 587
    username: ${spring.mail.username}         # 시크릿 파일에서 가져옴
    password: ${spring.mail.password}         # 시크릿 파일에서 가져옴
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

oci:
  objectstorage:
    namespace: ax5ipvulwvc1        # OCI Object Storage namespace
    bucket: bucket-20250507-1731   # OCI Object Storage bucket name
    uri-prefix: https://ax5ipvulwvc1.objectstorage.ap-chuncheon-1.oci.customer-oci.com
    par-url-prefix: https://ax5ipvulwvc1.objectstorage.ap-chuncheon-1.oci.customer-oci.com/p/lcHjyXH-Qpc4Z7LTiUpDo4E3TjB1i9-bop52n361zIRHh2TLjnHKxzjL7S7vufPK/n/ax5ipvulwvc1/b/bucket-20250507-1731/o/


email:
  from: admin@lumidiary.com

jwt:
  secret: bXlzZWNyZXRrZXlteXNlY3JldGtleW15c2VjcmV0a2V5MTIzNDU2
  expiration: 86400000
  verification-expiration-ms: 900000

app:
  client:
    url: "https://lumidiary.com"

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.config: DEBUG