apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: default
type: Opaque
stringData:
  spring.datasource.username: "root"
  spring.datasource.password: "Lumidiary123!"
  spring.mail.username: "ocid1.user.oc1..aaaaaaaakcyiu3bglvqf6zg5i5gsyjdswwnwy6zqutng3a4s2gr57oa6luzq@ocid1.tenancy.oc1..aaaaaaaa7ojitcbuim62vslmfrxlggwmy2gogk7oxrldua3z424vvqypkjfq.un.com"
  spring.mail.password: "i[0-fCt$ZW+((elj5g0Z"